<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Reenus-MBP" name="com.Android.matchstats.LoginApp" tests="3" failures="0" timestamp="14 Jul 2017 14:28:11 GMT" time="50.785" errors="1">
  <testcase name="OpenApp" time="27.163" classname="com.Android.matchstats.LoginApp"/>
  <testcase name="TakeScreenShot" time="1.780" classname="com.Android.matchstats.LoginApp">
    <error type="java.io.IOException" message="Source &#039;/var/folders/1f/64bh46510zb0_lwr2b4b0nhr0000gn/T/screenshot5909621274351418137.png&#039; exists but is not a directory">
      <![CDATA[java.io.IOException: Source '/var/folders/1f/64bh46510zb0_lwr2b4b0nhr0000gn/T/screenshot5909621274351418137.png' exists but is not a directory
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1371)
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1261)
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1230)
	at com.Android.matchstats.LoginApp.TakeScreenShot(LoginApp.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- TakeScreenShot -->
  <testcase name="LoginApp" time="21.842" classname="com.Android.matchstats.LoginApp"/>
</testsuite> <!-- com.Android.matchstats.LoginApp -->
